{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "prometheus-mktxp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-mktxp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "prometheus-mktxp.selectorLabels" . | nindent 6 }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end }}
