{{- if not .Values.config.scrapper.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-mktxp.fullname" . }}-scrapper-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "prometheus-mktxp.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config: {{- .Values.config.scrapper.value | toYaml | indent 1 }}
{{- end -}}
