apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-mktxp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-mktxp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "prometheus-mktxp.selectorLabels" . | nindent 4 }}
